### ISSUE TITLE
Simplify response structure verification from gremlin server in deserializer classes.

### ISSUE THREAD

**Issue by debasishdebs** [JanusGraph/janusgraph-python#17]
Currently, the deserializer class (GeoshapeDeserializer) has very deep level of indentation for checking the validity of response object from Gremlin server. That needs to be simplified.

Based on comment from @mbrukman , and looking at file [GeoShapeDeserializer](janusgraph-python/src/main/python/janusgraph_python/serializer/GeoShapeDeserializer.py) we see very deep level of indendation.

We can modify that into following structure:
```
if not some_condition():
    raise SomeError

if not some_other_condition():
    raise AnotherError

...

# now, only valid cases remain
```
Based on following [comment](https://github.com/JanusGraph/janusgraph-python/pull/4#discussion_r245533591l)

**Comment by FlorianHockmann** [comment]
Closing as it's no longer valid now that we have merged a first version of the library that is not based on these initial PRs.
