### ISSUE TITLE
Move Geoshape to GeoJSON util code as part of PointSerializer and CircleSerializer classes.

### ISSUE THREAD

**Issue by debasishdebs** [JanusGraph/janusgraph-python#18]
Why is this serialization implemented in `utils` and not in `serializer` like the other serialization logic? This is a really confusing place. Also the name doesn't hint at the fact that it only applies to GeoShapes.
I would instead create a `PointSerializer` and a `CircleSerializer` and put them into the `serializer` folder.

_Originally posted by @FlorianHockmann in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MTkxOTcxOTk1/pull_request_reviews/more_threads_

**Comment by FlorianHockmann** [comment]
Closing as it's no longer valid now that we have merged a first version of the library that is not based on these initial PRs.
