### ISSUE TITLE
Create Integration tests for Client to test for attributes.

### ISSUE THREAD

**Issue by debasishdebs** [JanusGraph/janusgraph-python#19]
Currently only unit tests are developed for the version of client in PR. Based on @FlorianHockmann 's [comments on on PR#4](https://github.com/JanusGraph/janusgraph-python/pull/4#discussion_r247564216).

The Integration tests needs to start a docker container with GraphOfGods loaded, and needs to query into the running docker and check for validity of response.

**Comment by debasishdebs** [comment]
Current PR #20 has integration tests for TextAttributes but the same is missing for ClientManager and GeoAttributes. Those needs to go in follow up PR.

**Comment by FlorianHockmann** [comment]
Closing as it's no longer valid now that we have merged a first version of the library that is not based on these initial PRs and which also contains integration tests.
