### ISSUE TITLE
Remove hardcoded credentials for Travis

### ISSUE THREAD

**Issue by debasishdebs** [JanusGraph/janusgraph-python#28]
Remove Hardcoded username and password used currently in Travis CI (.travis.yml) file. They need to be passed as secret env variable.

I'll remove the current instances of all hard coded credentials and do a force re push. Once removed and pushed, @chupman will then take care of setting env vars (from Travis UI) and accordingly update the env vars in `travis.yml`

**Comment by FlorianHockmann** [comment]
Closing as it's no longer valid now that we have merged a first version of the library that is not based on these initial PRs.
