### ISSUE TITLE
Migrate to `testcontainers` from `docker` library for client

### ISSUE THREAD

**Issue by debasishdebs** [JanusGraph/janusgraph-python#36]
`testcontainers-python` is widely used containerization library used for integration tests. The pros of the library `docker` which is used currently is that, it provides methods to get the `host ip` which is very much needed to connect to `gremlin-server` as part of integration tests which is currently retrieved using `Popen` which is a security venerability. 

Also, [dotnet](https://github.com/JanusGraph/janusgraph-dotnet) library uses the same package ( `testcontainers` ) for containerization, and hence for consistency, moving python client to `testcontainers-python` seems a good idea too.

**Comment by FlorianHockmann** [comment]
No longer valid (the current version uses Testcontainers).
