### ISSUE TITLE
Update Travis CI to include Miniconda in env

### ISSUE THREAD

**Issue by debasishdebs** [JanusGraph/janusgraph-python#8]
Currently, Travis build use pure python for versions specified to execute all python scripts and build the project.

Since, we are going to start adding *Anaconda* as pre-requisite for using the library, we will be moving all of builds to start using Anaconda.

The #7 takes care of creating automated script to generate docs, which was earlier done using Pure python evns. Now that is moved to Anaconda.

The Travis build needs to include Anaconda/Miniconda so that build happen using Anaconda. 

Also, if possible we will need to add building of docs script to Travis build.

**Comment by sjudeng** [comment]
Is it possible to avoid requiring Anaconda? It might make it more portable to instead declare the specific required dependencies in a requirements.txt file. This approach might also make it easier to identify what dependencies (and licenses) are being added during code reviews of future contributions.

As far as Travis goes, Docker might be a good option. I think a base python:3 image with dependencies installed from requirements.txt would be good but the base image also could be anaconda though it's huge (3.5G).

**Comment by debasishdebs** [comment]
@sjudeng : I see your point. The reason why I wanted to include Anaconda, was to use anaconda envs and managing using Python's pure virtualenv is bix complex.

I was anyways adding Miniconda, which is 125MB in size. But still having that heavy file in builds, and pre-requisite doesn't seem clean.

I've fixed this, and pushed a new commit, which removes usage of Anaconda, Removed download of anaconda in our builds, and rather uses only *virtualenv* to create envs. The same is done and builds are working. As for support, I'm supporting Python > 3.3.

Do we add requirements.txt? I don't think that will be needed as PyBuilder takes care of that, and downloads all dependencies while building the library.
